### ISSUE TITLE
Error when auto updating the exe on Windows 11

### ISSUE THREAD

**Issue by chr0m** [mattpannella/pocket-updater-utility#217]
The zip file downloads ok, but then throws this error after press 'i' to install

```
Would you like to [i]nstall the update, [c]ontinue with the current version, or [q]uit? [i/c/q]: i
An error occurred: FileNotFoundException:System.IO.FileNotFoundException:
File name: 'System.IO.Pipes, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.InternalLoad(ObjectHandleOnStack , ObjectHandleOnStack , StackCrawlMarkHandle , Boolean , ObjectHandleOnStack , ObjectHandleOnStack )
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName , RuntimeAssembly , StackCrawlMark& , Boolean , AssemblyLoadContext )
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName , StackCrawlMark& , AssemblyLoadContext )
   at System.Reflection.RuntimeAssembly.InternalLoad(String , StackCrawlMark& , AssemblyLoadContext )
   at System.Reflection.Assembly.Load(String )
   at Program.UpdateSelfAndRun(String directory, String[] updaterArgs)
```
I tried from sd card and from a local folder with the same result

**Comment by mattpannella** [comment]
did you rename the exe

**Comment by chr0m** [comment]
Nope, it's just the default name of pocket_updater.exe

It seems strange. pocket_updater.zip downloads ok, but then I get the FileNotFoundException.

It's not a big deal really if it's not happening for others. I just extract the zip file and overwrite the existing .exe and I'm good to go.

I'm sure it worked the first time I updated though. I've only had the Pocket for a week or so, but I used your tool to prepare before I actually started using the Pocket.

**Comment by claytankozmo** [comment]
Just wanted to chime in and say same for me too today, but not any other time.

**Comment by AceHeartTron** [comment]
I can also confirm an issue with the update function on Windows 10.  The new pocket_updater.zip downloads, but when press "I" to install, I don't get the error described above.  Instead the terminal window simply closes and the application would appear to have terminated without proceeding with the usual process to rename the existing .exe and extracting the new one.

**Comment by mattpannella** [comment]
still trying to figure out whats going on here
because the app throws up messages before it tries to do anything with the files, and this error is popping before that

**Comment by JayCeeDC** [comment]
same for me when updating from 2.42.0

```
I:\>pocket_updater.exe
Pocket Updater Utility v2.42.0
Checking for updates...
A new version is available. Downloading now...
Download complete.
I:\pocket_updater.zip
Go to https://github.com/mattpannella/pocket-updater-utility/releases/tag/2.43.0 for a change log
Would you like to [i]nstall the update, [c]ontinue with the current version, or [q]uit? [i/c/q]: i
An error occurred: FileNotFoundException:System.IO.FileNotFoundException:
File name: 'System.IO.Pipes, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.InternalLoad(ObjectHandleOnStack , ObjectHandleOnStack , StackCrawlMarkHandle , Boolean , ObjectHandleOnStack , ObjectHandleOnStack )
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName , RuntimeAssembly , StackCrawlMark& , Boolean , AssemblyLoadContext )
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName , StackCrawlMark& , AssemblyLoadContext )
   at System.Reflection.RuntimeAssembly.InternalLoad(String , StackCrawlMark& , AssemblyLoadContext )
   at System.Reflection.Assembly.Load(String )
   at Program.UpdateSelfAndRun(String directory, String[] updaterArgs)
```

**Comment by mattpannella** [comment]
i just reproduced this in windows. i think i have an idea of whats going on, will get the patch into the next release

**Comment by Shadow322** [comment]
i get a instant crash after taping i from v2.42.0 to v2.43.0 happen the same before with previous to v2.42.0

**Comment by Tikishark777** [comment]
I have the same issue.  The only way to update is to copy over the updated exe file and try again.  Otherwise, everything works as planned.

**Comment by mattpannella** [comment]
has this been resolved for everyone?

**Comment by chr0m** [comment]
Just updated and it worked! So looks like it has been fixed. Thanks!
